const express = require('express');
const app = express();
const bodyparser = require('body-parser');
const fs = require('fs');

fs.writeFileSync('./fspractice/text.txt', 'hello');

// Question 1
// Write a file that has 100 numbers. All of them are whole numbers. There is 1 number per line.
// Do it with the writeFile and writeFileSync functions of the fs module

const writeHundredNumbers = () => {
    let arr = [];

    for (let i = 0; i < 100; i++) {
        arr = arr.concat(i);
    }
    let newArr = arr.join('\n');
    fs.writeFileSync('./fspractice/question1.txt', newArr);
};

writeHundredNumbers();

// Question 2
// Write a file that has 10 random numbers. All of them are whole numbers. There is 1 number per line.

const writeRandomNumbers = () => {
    let arr = [];

    for (let i = 0; i < 11; i++) {
        arr = arr.concat(Math.floor(Math.random() * i));
    }
    let newArr = arr.join('\n');
    fs.writeFileSync('./fspractice/question2.txt', newArr);
};

writeRandomNumbers();

// Question 3
// Write a program that reads the file generated by the previous question and gives you the sum of all the numbers.

const randomNumberSum = () => {
    let nums = fs
        .readFileSync('./fspractice/question2.txt')
        .toString()
        .split('\n');

    newNums = nums.map(x => {
        console.log(x);
        return Number(x);
    });
    console.log(newNums);
    let sum = newNums.reduce((x, y) => x + y, 0);
    console.log(sum);
    fs.writeFileSync('./fspractice/question3.txt', sum);
};

randomNumberSum();

// Question 4
// Write a program that reads the file generated in question 2, reverses it, and writes it back to the file. In other words, the number of the first line becomes the number of the second line.

const reverse = () => {
    let input = fs
        .readFileSync('./fspractice/question2.txt')
        .toString()
        .split('\n')
        .reverse()
        .join('\n');
    console.log(input);
    fs.writeFileSync('./fspractice/question4.txt', input);
};

reverse();
